#definisce la porta custom per tomcat rispetto a quella definita di default su quello embedded
server:
     port: 8888

#definisce la configurazione custom verso una coda di messaggi ActiveMQ esterna da quella Embedded 
#MongoDB custom config
#spring:
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#  data:
#    mongodb:
#      uri:mongodb://username:password@host:port
#      database: sausmagic
#      port: 27017

#Serve a configurare Spring security. Configura l'utente e la password per accedere alla root di tomcat
security:
  user:
    name: sausmagic
    password: sausmagic